[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/wp-admin/*"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  status = 302

[[redirects]]
  from = "/wp-login/*"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  status = 302

[[redirects]]
  from = "/api/ffns/*"
  to = "https://us-central1-husseyfns.cloudfunctions.net/app/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/api/hfns/*"
  to = "http://husseyfns.herokuapp.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 302