[build]
  command = "npm run build"
  publish = "public"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api/ffns/*"
  to = "https://us-central1-husseyfns.cloudfunctions.net/app/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
